// Generated by CoffeeScript 1.9.2
(function() {
  define(function(require, exports, module) {
    var AppInit, ExtensionUtils;
    ExtensionUtils = brackets.getModule('utils/ExtensionUtils');
    AppInit = brackets.getModule('utils/AppInit');
    return AppInit.appReady(function() {
      return ExtensionUtils.loadStyleSheet(module, 'main.less');
    });
  });

}).call(this);
